### ISSUE TITLE
Not supported with laravel 6.3

### ISSUE THREAD

**Issue by dpkpaa** [talvbansal/media-manager#102]
Can you update this for laravel 6.3 support ?

**Comment by talvbansal** [comment]
Hey thanks for checking this out,

The package is a little out of date and still uses Bootstrap 3, if you'd like to PR the bootstrap 4 UI then I could make the back end changes for Laravel 6.* quite quickly.

Thanks

Talv

**Comment by Nirys** [comment]
@talvbansal , my PR should have fixed this, but it needs a release tag update.  Are you able to tag it please?

**Comment by talvbansal** [comment]
Do we not need to bump / add to these these in `composer.json` to make this work for Laravel 6+?

```
    "illuminate/support": "5.*",
    "illuminate/routing": "5.*",
```

**Comment by talvbansal** [comment]
Done and tagged
