### ISSUE TITLE
buttons

### ISSUE THREAD

**Issue by proibo** [talvbansal/media-manager#128]
I have a problem all buttons doesn't work except upload button

**Comment by talvbansal** [comment]
Hi can you check this repo for a working example

https://github.com/talvbansal/media-manager-laravel-example

**Comment by proibo** [comment]
hi i checked already and it's same but still have problem

**Comment by talvbansal** [comment]
the demo doesnt work for you?

**Comment by proibo** [comment]
yes can you help me please
this is my email
***@***.***
