### ISSUE TITLE
showMediaManager is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by matyre73** [talvbansal/media-manager#26]
Hi

Hope you can point me in the right direction. When I load the page, in chrome dev tools I get the warning from vue below.

[Vue warn]: Property or method "showMediaManager" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in root instance)

When I check vue devtools it picks up on the root  that data variables have been set. When I click the button the data values change accordingly.

showMediaManager goes from false to true but the modal does not show. 

I am loading the css and the js files straight into the page.

Any help would be greatly appreciated.

**Comment by matyre73** [comment]
Well I got it showing up but now i have the below error.

Uncaught (in promise) TypeError: Cannot read property 'error' of undefined
    at s.eval (eval at <anonymous> (admin-8ef054359d.js:89), <anonymous>:29:17708)

It is not showing the folders or anything as this error keeps popping up.

**Comment by talvbansal** [comment]
Hey @matyre73 sorry you're having problems, can you post some code for me please so i can try and see what you're doing? Hopefully its something easy to fix and we can use this to help improve the documentation!

**Comment by talvbansal** [comment]
@matyre73 any update?
