### ISSUE TITLE
[Suggestion] Validating empty inputs

### ISSUE THREAD

**Issue by austintoddj** [talvbansal/media-manager#3]
Perhaps it'd be more user-friendly to validate empty form inputs to prevent someone from submitting on the `Rename Item` modal. It appears to work correctly on the `Add Folder` modal, it won't submit without putting something in the form.

Currently an ugly error shows up behind the modal. Just a UI fix, does not hamper actual functionality.

![screen shot 2016-09-27 at 3 03 13 pm](https://cloud.githubusercontent.com/assets/8037011/18889839/588cc18c-84c4-11e6-8c91-577be32441d3.png)

**Comment by talvbansal** [comment]
Good spot! I'm on it now! :)

**Comment by talvbansal** [comment]
Fixed in release v1.0.4
