### ISSUE TITLE
Custom styling

### ISSUE THREAD

**Issue by ruchern** [talvbansal/media-manager#31]
Hi,

I really like this Media Manager after using Canvas.

Is it possible that I can create custom styling for the media manager to include thumbnails and stuff like this?

Also, in order to do that, I will have to modify the files in the `vendor` directory. In order to see the changes, I have to publish each time files are being modified.

Is there a quick help where i can change the code to publish the original files into my project's `resource` directory?

I am currently looking at the file `src/Providers/MediaManagerServiceProvider.php` 

```php
private function defineResources()
    {
        $this->publishes([
            MEDIA_MANAGER_BASE_PATH.'/resources/assets' => resource_path('/assets/talvbansal/media-manager'),
        ], 'media-manager');
    }
```

Is this alright?

**Comment by talvbansal** [comment]
@ruchern thank you so much for checking out the media-manager, I'm really excited that you like it!

Currently publishing the assets that you've looked at will give you the files that have been run through webpack. If want to make changes to the ui you'd need to edit the sass and js files within the `resources/assets` folder after forking the project.

I'd love to see what changes you have in mind so if you do have any ideas please do make a pull request! :D

**Comment by ruchern** [comment]
@talvbansal I'm trying to get thumbnails for images instead of just a plain list view on the directory level before clicking on anything.

And trying to get Bootstrap 4 to work because my project is using it.

**Comment by talvbansal** [comment]
Having an thumbnail view as well as a list view would be a great new feature! - Please do make a PR with the changes you make!

I'll have to have a think about how to make Bootstrap 4 work with this. It probably makes sense for me to bundle a set of additional styles for the media manager so that it doesn't rely on any css framework to get up and running and then those can be overridden ?
