### ISSUE TITLE
Adding permissions and privileges to determine who can view a file or folder 

### ISSUE THREAD

**Issue by nwaughachukwuma** [talvbansal/media-manager#37]
Hi @talvbansal  and everyone I am developing an application where users in the system have permissions and roles, and on this basis, the users can only view the files or folder which their permissions or privilege grants them. Is it possible to achieve it with this or is there another package I may need to install on this one?

**Comment by talvbansal** [comment]
Hi @nwaughachukwuma, thanks for checking out this package! User permissions aren't something thats been discussed when developing the media manager so thanks for bringing it up. Can you think of a way that we can restrict access to the items?

**Comment by nwaughachukwuma** [comment]
Hi @talvbansal check this project https://github.com/sjarvela/kloudspeaker

**Comment by talvbansal** [comment]
@nwaughachukwuma just thinking about this even if you limited which files the media manager displayed as the files are stored on a public disk if someone figured out the url to another users file they'd still be able to view it.

**Comment by nwaughachukwuma** [comment]
Hi @talvbansal have you seen this (https://github.com/sroutier/laravel-enterprise-starter-kit) application? Here, you can determine which route a user can see based on the permission they are assigned. And this is done using the middleware, which sends any user without permission to a given route, back to the dashboard, or throws a 403 error (You cannot view this page).

I feel that if such feature is added to this already awesome package, it will make it more interesting. And Laravel can handle it.

**Comment by talvbansal** [comment]
@nwaughachukwuma im not sure i know how this would work, if you can see a way to make this work please can you submit a pull request. Id be really excited to see what you come up with!

**Comment by talvbansal** [comment]
Hi @nwaughachukwuma any update with guys on your end?

If not I might close this out

**Comment by nwaughachukwuma** [comment]
Yeah you can go ahead please. Thanks for your time
