### ISSUE TITLE
Creating and deleting folders causes Problems

### ISSUE THREAD

**Issue by Brotzka** [talvbansal/media-manager#41]
Hey,

I have some Problems creating and deleting folders. When I create a folder, it's listed like shown on the image:
![bildschirmfoto 2017-05-29 um 18 40 50](https://cloud.githubusercontent.com/assets/9106911/26557004/782e7630-449e-11e7-9bdc-e81b3842a77f.png)
The folder is created and has its original name. I can rename and move files in it. But it's not possible to delete or open the folder. When I try to delete such folder, I get a 400 - Bad Request notification and the following error message
```
{error: "unlink(/home/vagrant/Projekte/laravel-blog/storage/app/public/test1): Is a directory"}
error
:
"unlink(/home/vagrant/Projekte/laravel-blog/storage/app/public/test1): Is a directory"
```

Any idea how to solve this?

**Comment by talvbansal** [comment]
Hi @Brotzka,

Thanks for bringing this to my attention, I've been working on upgrading some of the JS code to ES6 so theres a chance I've missed something here whilst I've been learning, I'll look into this ASAP!

**Comment by Brotzka** [comment]
Thanks!

**Comment by talvbansal** [comment]
Hi @Brotzka ive just taken a look at this on the master branch and I cant repeat the issue, can you check that you've pulled in the latest set of changes please?

**Comment by talvbansal** [comment]
@Brotzka any update on your end?

**Comment by Brotzka** [comment]
No.. I think it's because I've made some changes in my Elixir/Mix-Config. I've tested your package within a fresh installation and everything works fine.
