### ISSUE TITLE
It would be nice to implement it similar to the Octobercms average

### ISSUE THREAD

**Issue by webpackages** [talvbansal/media-manager#46]
![captura](https://user-images.githubusercontent.com/5165935/27269937-66175786-5480-11e7-8be4-83afef9da16a.PNG)

https://octobercms.com/

**Comment by talvbansal** [comment]
Hi,

Thanks for checking out the media manager. Is there anything specific you'd like to see from the screenshot?

I'd love for contributions so if you have the skills please to make a PR for the changes you'd like to see!

Thanks!
