### ISSUE TITLE
Binding selected value and modal cannot close

### ISSUE THREAD

**Issue by folkevil** [talvbansal/media-manager#48]
Hi, 
 I'm trying to select image from media modal and insert it to form. But i can't bind selected value to input field. 
 After selected modal also not close too. 

This is my code
` <input type="text" class="form-control" id="image" name="image"/>

                                <a class="input-group-addon" @click="showMediaManager = true">
                                    <i class="fa fa-folder-o"></i>
                                </a>

                                <media-modal v-if="showMediaManager" @media-modal-close="showMediaManager = false">
                                <media-manager
                                        :is-modal="true"
                                        :selected-event-name="image"
                                        @media-modal-close="showMediaManager = false"
                                >
                                </media-manager>
                                </media-modal>
`
and script
`<script>

        new Vue({
            el: '#create-role',
            data: {
                showMediaManager: false,
                selectedEventName: 'image'
            },

            created: function () {
                window.eventHub.$on('media-manager-selected-image', function (file) {
                    // Do something with the file info...
                    console.log(file.name);
                    console.log(file.mimeType);
                    console.log(file.relativePath);
                    console.log(file.webPath);
                    // Hide the Media Manager...
                    //$('#source').val(file.relativePath);
                    $(this).selectedEventName = file.relativePath;

                    $('#preview-image').html('<img class="img-responsive" src="' + file.webPath + '">');

                    // Hide the Media Manager...
                    //$('.media-modal').hide();
                    this.showMediaManager = false;
                });
            }

        });
    </script>
`

**Comment by talvbansal** [comment]
Hi @folkevil,

Heres some sample code that im using that does something similar to what you're trying to achieve, let me know how you get on with it:

```html
    <media-modal v-if="showMediaManager" @media-modal-close="showMediaManager = false">
        <media-manager
                :is-modal="true"
                selected-event-name="editor"
                @media-modal-close="showMediaManager = false"
            >
        </media-manager>
    </media-modal>

    <div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="page_image" id="page_image" alt="Image thumbnail" placeholder="Page Image" v-model="pageImage">
            <span class="input-group-btn">
                <button type="button" class="btn btn-default" @click="showMediaManager = true">Select Image</button>
            </span>
        </div>

        <div>
            <img v-if="pageImage" class="img img-responsive" id="page-image-preview" style="margin-top: 3px; max-height:250px;" :src="pageImage"/>
            <span v-else class="text-muted small">No Image Selected</span>
        </div>
    </div>
```

```javascript
const app = new Vue({
    el: '#app',
    data: {
        showMediaManager: false,
        pageImage : null,
    },
    mounted(){
        window.eventHub.$on('media-manager-selected-editor', function (file) {
            // Do something with the file info...
            console.log(file.name);
            console.log(file.mimeType);
            console.log(file.relativePath);
            console.log(file.webPath);
            this.pageImage = file.webPath;

            // Hide the Media Manager...
            this.showMediaManager = false;
        }.bind(this));
    }
});
```

**Comment by folkevil** [comment]
@talvbansal thank you, it's work :D

**Comment by talvbansal** [comment]
@folkevil no problem !
