### ISSUE TITLE
Unknown custom element: <media-manager>

### ISSUE THREAD

**Issue by KekoApp** [talvbansal/media-manager#52]
Hi there, I've installed following the instructions in the readme.

I think the issue is to do with not using Vue.component in the app.js - but I'm really not sure

`Unknown custom element: <media-manager> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

Happens on load of a page with nothing but the <media-manager> tag

**Comment by KekoApp** [comment]
Bit more info, if i set up the app.js like this:

`Vue.component('media-manager', require('./media-manager'));`

I then see the media manager load on the site, however i get JS error:

`TypeError: e.data is undefined`

**Comment by talvbansal** [comment]
Hi @KekoApp,

Thanks for checking out the media-manager, please can you look at the example attached in this issue:

https://github.com/talvbansal/media-manager/issues/42

Thanks

**Comment by talvbansal** [comment]
This issue also looks similar to yours:

https://github.com/talvbansal/media-manager/issues/30

**Comment by ruchern** [comment]
@KekoApp Which project are you using this with? Laravel or some other JS project?

**Comment by KekoApp** [comment]
@ruchern Laravel 5.4, is a fresh install apart from debugbar

**Comment by KekoApp** [comment]
I've checked the linked issues and mine does seem to be different.

my app.js

```
window.Vue = require('vue')

require("./../../talvbansal/media-manager/js/media-manager");

// Use trans function in Vue (equivalent to trans() Laravel Translations helper). See htmlheader.balde.php partial.
Vue.prototype.trans = (key) => {
  return _.get(window.trans, key, key)
}

Vue.component('login-form', require('../components/admin/auth/LoginForm.vue'))
Vue.component('email-reset-password-form', require('../components/admin/auth/EmailResetPasswordForm.vue'))
Vue.component('reset-password-form', require('../components/admin/auth/ResetPasswordForm.vue'))

```

my web.php routes file has the route inserted like:

```
Route::group(['prefix' => 'a'], function () {

    \TalvBansal\MediaManager\Routes\MediaRoutes::get();

    Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
```

and the media-manager config file looks like:

```
return [

    'routes' => [
        'middleware' => [],
        'prefix'     => env('MEDIA_MANAGER_ROUTE_PREFIX', '/a/'),
    ],

    'disk' => env('MEDIA_MANAGER_STORAGE_DISK', 'public'),
];
```

I can also access a test image I've put in the public storage folder, so all is ok there.

My view simply calls:

`<media-manager prefix="/a/"></media-manager>`

When I go to the page, I can see the media-manager loaded, however the loading spinner is going and I get the javscript error in console:

`TypeError: e.data is undefined`

**Comment by KekoApp** [comment]
![image](https://user-images.githubusercontent.com/1787216/27583656-fb031e0e-5b2c-11e7-9a5e-9956a96d8b0d.png)

**Comment by talvbansal** [comment]
what are you seeing in your network tab?

**Comment by KekoApp** [comment]
No XHR going on there, all 200 ok on css / js etc

**Comment by talvbansal** [comment]
Hi @KekoApp,

You're going to need to upload an example for me to investigate this further.

**Comment by KekoApp** [comment]
I'm pretty this error is from laravel 5.4 Vue no longer using vue-resource.

Will try install it and report back

**Comment by talvbansal** [comment]
@KekoApp thanks! 

If it is vue-resource issue i'd e great if you could submit a PR with the changes needed to upgrade to axios!

**Comment by KekoApp** [comment]
It's definitely related to the overhaul vue has had in laravel 5.4 - I'm going to try get it working in my current project then hopefully sort out a PR.

Much appreciated all your help here!
