### ISSUE TITLE
[Suggested Feature] Hover State 

### ISSUE THREAD

**Issue by austintoddj** [talvbansal/media-manager#54]
Gmail has a nice little hover state when dragging mail attachments into a new message. It looks like this:

<img width="572" alt="screen shot 2017-07-11 at 11 46 04 am" src="https://user-images.githubusercontent.com/8037011/28079651-db8e1e72-662e-11e7-81cc-9c3457375625.png">

I know there is already a black border when a file is dragged over, but perhaps the Media Manager could benefit from a more user-friendly hover state like this?

**Comment by talvbansal** [comment]
Great shout! - I'll take a look into getting this done. It should be totally do-able with a bit of css! 👍

**Comment by talvbansal** [comment]
I've updated the border styles for this but I'm not 100% sure on how I'm going to get some useful text into the target area just yet!

**Comment by austintoddj** [comment]
Sweet! Can't wait to check it out. I'll close this out as soon as I take a look 👍

**Comment by talvbansal** [comment]
@austintoddj i think we need to leave this open until we can figure out how to do the hover over text. The styles are an improvement but I dont feel like this is really done until we have the supporting text.

BTW thanks for these suggestions, I really really appreciate these little details that go a long way in making the package feel more polished. @trashpants usually looks over this sort of stuff for me but I don't think he's looked at this package yet - @trashpants maybe you could look into this if you get a chance and make this your first commit on github as well as getting some Vue Js practise in!
