### ISSUE TITLE
[Suggested Feature] Directions when Empty

### ISSUE THREAD

**Issue by austintoddj** [talvbansal/media-manager#55]
Dropbox gives a nice message to users when the particular folder you're located in is empty. It looks like this:

![empty-folder](https://user-images.githubusercontent.com/8037011/28079805-5ba0856e-662f-11e7-9007-35eac499f9b2.jpg)

Maybe a little image or messaging could help users see very quickly the capability of Drag and Drop, as well as a placeholder.

**Comment by talvbansal** [comment]
Totally agree this would be a nice little improvement, thanks for the suggestion!
