### ISSUE TITLE
Media manager in production on shared hosting

### ISSUE THREAD

**Issue by Exoseed** [talvbansal/media-manager#56]
Hi,

You helped me some weeks ago to solve an issue I had with this plugin, but now that I'm trying to go in production mode, there's a new one I can't resolve.
I have a shared hosting with no working SSH access, which is a real problem. When I uploaded my site via FTP, the links to the assets uploaded via the media-manager were all wrong.

A rough solution I found to make them work again was to copy all the content of \storage\app\public to the root \storage. Obviously, it's not ideal but it does solve one part of the problem.
The thing is, in my admin, the media-manager uploader can't seem to find any asset uploaded. It says "0 items" so I can only guess the plugin can't find the right path for some reason. Thing is it worked on localhost...

Any idea of what might be the issue there? Thanks a lot in advance!

**Comment by talvbansal** [comment]
Hi @Exoseed,

So it sounds like the link to your storage folder normally created by `php artisan storage:link` hasnt been created which is causing your problem.

I'm not 100% sure on how we can get around the sym link issue: if you have sftp not just ftp this page might have a solution:

https://stackoverflow.com/questions/5589489/create-symbolic-links-on-server-without-ssh-available

I'm more than happy to help but it would require me having access to your server, if you want to discuss this further you can message me on twitter @talv :)

**Comment by Exoseed** [comment]
Ok so that's kinda weird because I managed to create a link from the public/storage folder to the storage/app/public folder via SFTP and WinSCP but it still doesn't work for some reason.
Maybe the issue come from a workaround I had to implement in order to remove the "public" part of the URL once in production.

I had to rename the server.php file at the root of my application in index.php and change the .htaccess a bit like so:

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteRule ^(.*)/$ /$1 [L,R=301]

	RewriteCond %{REQUEST_URI} !(\.css|\.js|\.png|\.jpg|\.gif|robots\.txt)$ [NC]
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteRule ^ index.php [L]

	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_URI} !^/public/
	RewriteRule ^(css|js|images)/(.*)$ public/$1/$2 [L,NC]
</IfModule>
```

Do you think the issue could come from there?

**Comment by talvbansal** [comment]
Hi @Exoseed, 

Without seeing the whole setup and looking at the server logs im not really sure that i can offer any better advice at this point.

In your access log are requests to your assets still going to `/storage/image-name.jpg`?

**Comment by Exoseed** [comment]
Hi,

Thing is it's my work server, so I can't really give you access to it. I would if it was just a personal project :/
The website's here: [nicefilmfestival.com/ufctc2017](http://www.nicefilmfestival.com/ufctc2017/)

As you can see, the assets load properly but only because I moved all the content of \storage\app\public to the root \storage as I was saying above.
So the issue is that even if the symlink exist, for some reason I can't link assets stored in \public\storage and so I guess that's why the media-manager can't find them in my admin page.

It's probably because I removed the "public" part of the url though...

**Comment by talvbansal** [comment]
Hi @Exoseed,

looks like you've moved your `/storage` folder into `/public/storage` as i can see all of your applications logs and session files as well as your assets which are additional problems in themselves.

Can you just check that the public disk in your `/config/filesystems.php` is pointing at the correct folder now, that is possibly the cause of the media-manager not locating the images.

https://github.com/laravel/laravel/blob/master/config/filesystems.php

Hope this helps!

**Comment by Exoseed** [comment]
No the /config/filesystems.php seems fine,
Another lead maybe: in my admin panel, I have a page dedicated to uploading assets with only the media manager in it. On this page I have this error 404:

`Failed to load resource: the server responded with a status of 404 (Not Found)`

For this path:

`http://www.nicefilmfestival.com/fonts/icomoon.ttf?b7cc673a78bf6c2daf8e8e3efcf8be31`

Which is normal because the path should be:

`http://www.nicefilmfestival.com/**ufctc2017**/fonts/icomoon.ttf?b7cc673a78bf6c2daf8e8e3efcf8be31`

In that case it only causes the font not to load, which messes up the styling a little but maybe that's the origin of the problem?

I'm really sorry to bother you with this, you're of great help but I'd really like to use this plugin on this project, otherwise I'd have to backup on a very less user-friendly more time-consuming solution..

**Comment by talvbansal** [comment]
Hi @Exoseed, 

within your .env file if you change the `APP_URL`  value to `http://www.nicefilmfestival.com/ufctc2017` does that fix the issue?

**Comment by Exoseed** [comment]
Already tried that, but it didn't change anything :/

**Comment by talvbansal** [comment]
Is there an environment or a project that you can set up that i can have access to that gives a repeatable issue? I'd like to help you but i really am just guessing at this point.

**Comment by talvbansal** [comment]
Hi @Exoseed have you had any luck with this?
