### ISSUE TITLE
Error 500 when uploading files

### ISSUE THREAD

**Issue by Dzhangar1980** [talvbansal/media-manager#57]
Hi
I develop site using laravel 5.3
And I installed you'r media-manager on local server (ubuntu 16 lts desctop).
All worked fine.
After deploy on VDS I taked some problems:
-  500 error when uploading files
- directories in DIV <table-responsive easel-file-picker-list> look as  
{ "name": "236", "mimeType": "folder", "fullPath": "/236", "modified": { "date": "2017-08-03 22:08:02.000000", "timezone_type": 3, "timezone": "Europe/Moscow" } } 

So, I can't open any directory and upload any file....

Please help me.
I puted:
chmod -R 777 storage
php artisan storage:link
ln -s storage/app/public /public/storage

**Comment by talvbansal** [comment]
Hi @Dzhangar1980, which version of the media-manager are you using? It looks like you need to run elixir / webpack to fix the issues you're having.

Let me know if that solves your problem!

Thanks

**Comment by Dzhangar1980** [comment]
Hi @talvbansal, I use last version. Yestoday I did composer update for my project.
I run Elixir now
Nothing fixed...
When upload image-file:
I have error on http://mysite/admin/browser/file
MethodNotAllowedHttpException in RouteCollection.php line 218:
On main (first) load page of meda-manager when I wont brouse my storage's directories and files:
[https://gyazo.com/484f66edbfa7272517c4148968b81680](url)

**Comment by talvbansal** [comment]
Hi @Dzhangar1980 

Can you make sure you re-publish the JS assets:
```
php artisan vendor:publish --tag=media-manager --force
```

Then run elixir.

Many thanks

Talv

**Comment by Dzhangar1980** [comment]
Hi @talvbansal 
I run commands:
php artisan vendor:publish --tag=media-manager --force
and
sudo gulp
...nothing fixed :-(

**Comment by talvbansal** [comment]
I've just cloned a fresh project down and followed the installation guide its working fine for me.

There is not much else i can do without looking at your code which im happy to do if you are.

Thanks

Tal

**Comment by Dzhangar1980** [comment]
What a code I must show you?...

**Comment by talvbansal** [comment]
All of the relevant pieces, if I can access the serve itself it'd be even better!

**Comment by Dzhangar1980** [comment]
You can get https://github.com/Dzhangar1980/liberty_pro

**Comment by Dzhangar1980** [comment]
use site.loc/administrator/mediamanager route

**Comment by talvbansal** [comment]
Hi @Dzhangar1980 - I've just cloned the project down and this has worked first time for me. I assume it'd be a permissions error on your end.

**Comment by Dzhangar1980** [comment]
ok. 
Let's do it:
visit to http://libertyclub.pro/cabinet using 
login: rybka.zolotaya.96@mail.ru
pass: d4v1Si
After go to http://libertyclub.pro/administrator/mediamanager
You have the code's copy... 
The blade page of MediaManager:
resources/views/administrator/mediamanager.blade.php

**Comment by Dzhangar1980** [comment]
Use you any messangers? ICQ, Skype, Telegramm, etc?

**Comment by talvbansal** [comment]
I have skype talv.bansal but i wont be available for a couple hours. :)

**Comment by talvbansal** [comment]
@Dzhangar1980 im free now if you need some help
