### ISSUE TITLE
I can not delete, rename or create folder, only upload file.

### ISSUE THREAD

**Issue by ssheduardo** [talvbansal/media-manager#59]
Hi,
I use your package in L5.3, the install and config is easy.
When upload file not have problem and the preview is fine but when try delete the file, create folder or rename that not make nothing.
In console I do not see errors.
Note: I work with adminlte.
Thanks you.

![error-mm](https://user-images.githubusercontent.com/1160138/29813170-7ea8f744-8ca9-11e7-870d-10f792689971.gif)

**Comment by talvbansal** [comment]
Hi @ssheduardo !

Thanks for checking this package out, can you tell me which version of the media-manager you're using and also would you be able to show me whats happening in your browsers network tab so that i can see if the requests are being sent for the delete / rename / create folder events.

Many thanks

Talv

**Comment by ssheduardo** [comment]
Hi, 
Send email to talvbansal@hotmail.com with a video.

**Comment by ssheduardo** [comment]
The solutions when work gulp is added to mix.styles (thanks you @talvbansal)  
My gulpfile.js

```
mix.styles(
        [
            "../talvbansal/media-manager/css/media-manager.css",
            "app.scss"
        ],'public/css/app.css'
    );

```
Remember do not included in app.scss the line
`"../talvbansal/media-manager/css/media-manager.css",`

![mm 1](https://user-images.githubusercontent.com/1160138/29899698-4662f188-8ded-11e7-8e26-1524ba4c4047.gif)

**Comment by talvbansal** [comment]
Hi @ssheduardo 

I'm glad  we got this resolved! Looks like i updated the documentation for laravel mix and didnt realise it would have the same impact for elixir. Do you fancy making a PR to the documentation with new notes on how to do this for users still using elixir?

Thanks

**Comment by talvbansal** [comment]
Also what are you using to create those gifs? :)

**Comment by ssheduardo** [comment]
For the creation of gif, first capture the screen with quitcktime later use a page online to export the mov -> gif.
