### ISSUE TITLE
TokenMismatchException

### ISSUE THREAD

**Issue by mckayze** [talvbansal/media-manager#64]
Not sure why im getting this since on my page ive included the code

`<script>
    window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
    ]); ?>
</script>`

Not sure what information to give for help other than saying i've followed the guide, but this error appears anytime i try any post actions with the media-manager

**Comment by ruchern** [comment]
Was your `<form></form>` for POST method handled properly with `{{ csrf_field() }}`?

**Comment by mckayze** [comment]
I'm not using a form I'm using the media-manager vue tag

**Comment by talvbansal** [comment]
You can alternatively try adding this in your header if you're using the latest version of the media-manager:

`<meta name="csrf-token" content="{{ csrf_token() }}">`

the code itself that adds the csrf-token to the axios headers is here:

https://github.com/talvbansal/media-manager/blob/master/resources/assets/js/base.js

If you console.log(Laravel.csrfToken) what is output?

**Comment by mckayze** [comment]
I will edit this question and get back to you first thing tomorrow since all my work is at work

But from what I remember Im not 100% certain that i have that main.js file. I have a near identical file that is app.js in the resources/assets/js directory though.

**Comment by talvbansal** [comment]
Hi @mckayze,

The contents of this file are bundled with the media-manager.js file so you dont need to do anything extra.

Keep us posted on whats going on on your end and if i can be of any assistance please let me know.

Thanks

Talv

PS I'd love to know where the package is being used!

**Comment by mflavius** [comment]
Hey morning @talvbansal, So my base.js file looks a little different you can see from here: 
http://codepad.org/clS185Fw

Is mine out of date or something? I've just installed it yesterday so that would be confusing. Ill do a bit more snooping and see if i can find the problem.

And im using it to build a blogging site template, this package takes care of so many problems and so many hours of coding its great!

**Comment by talvbansal** [comment]
Hi @mflavius,
Thanks for checking the package out - I'm glad its been useful for you! This really is a separate issue but should be easy to fix.

If you look here:

https://github.com/talvbansal/media-manager/blob/master/src/Services/MediaManager.php#L383

The url method for the disk driver prefixes the generated url with the APP_URL value defined in your .env file. So updating that to localhost:8000 should solved your issue.

```bash
//.env
APP_URL=http://localhost:8000
```

Let me know how you get on - if you have any more issues let me know in a separate thread please!

**Comment by mckayze** [comment]
@talvbansal Thats great thanks! Im mflavius btw, this media manager is great i look forward to future updates etc

**Comment by talvbansal** [comment]
Glad we solved this - if you have any ideas for future development i'd love to hear them!

**Comment by mckayze** [comment]
I will be sure to let you know :)
