### ISSUE TITLE
Media Manager Modal not closing

### ISSUE THREAD

**Issue by mckayze** [talvbansal/media-manager#67]
The media manager modal isnt closing when i click cancel or the x button in the top right corner after opening it up, it just hides my files / folders from view and remains on the page.

Image Example: https://imgur.com/a/DJrCx

Vue events are fired though: https://imgur.com/a/Xy0VZ

Just not sure why its not closing I have the @media-modal-close="showMediaManager = false" property on both media-modal and media-manager.

**Comment by talvbansal** [comment]
Sounds like you're using an old version of the media-manager js code and is probably the source of your issues.

The event name is `meda-manager-close` which in previous versions of the project used to be just `close` but it collided with other projects so i renamed the event.

Can you update to the latest version - republish your assets, re-run webpack and let me know how you get on.

Thanks.

**Comment by mckayze** [comment]
Hmm that's strange because i only installed this two days ago, I've gone through the code and can only find the "media-modal-close" event being emitted within the "close()" method.

I think my version is up to date, if its not then im not sure how to update it because i've changed the version and ran composer update but it says nothing to install or update.

**Comment by talvbansal** [comment]
![screenshot from 2017-09-07 07-06-27](https://user-images.githubusercontent.com/7305131/30160627-44c2e942-939b-11e7-8d63-3f2041b4debe.png)

This is what my version looks like - empty folders have place holder text and the event is media-manager-close

**Comment by mflavius** [comment]
My composer.json shows this version `"talvbansal/media-manager": "^2.5"` and i have re-run webpack and rebundled the assets.

My temporary fix of course is to listen for the close event instead since im not using any other packages right now.

**Comment by talvbansal** [comment]
Did you republish the assets before re-bundling?

**Comment by mflavius** [comment]
`php artisan vendor:publish --tag=media-manager --force` followed by `npm run watch` is how i did it

**Comment by talvbansal** [comment]
Hi @mflavius any update on this? is there anything else i can do to help you with this issue?

**Comment by mflavius** [comment]
@talvbansal Yeah i got it working with the temporary fix, but it seems more permanent not because ive not ran into anymore problems and this codes in production. I tried to re-publish but it didnt work. 

What ill do is the next time i use this in the future, if there's the same problem with all the newest versions of laravel and this media manager, i'll re-open this and let you know! 

Thanks again for the help

**Comment by talvbansal** [comment]
Okay thanks for letting me know - for future reference I've created a repo with the media-manager added to  a laravel project just so people can see it being used

https://github.com/talvbansal/media-manager-laravel-example
