### ISSUE TITLE
Preview image default

### ISSUE THREAD

**Issue by austintoddj** [talvbansal/media-manager#7]
In `MediaManger.vue` on line 127, we are saying if the file is an image, then preview that image in the sidebar. What if we give an `else` to that statement to default an image preview to be something like `icon-file-text2` so the image doesn't just disappear altogether?

**Comment by talvbansal** [comment]
Good shout! 
Just made that change now! I wish i could figure out how to make the transition smoother but its in there now, take a look and let me know if you think the svg is too big or not!
