### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by mckenzieflavius** [talvbansal/media-manager#76]
I cannot access the media manager via modal, I cannot delete a file from the media manager page, I cannot delete a folder from the media manager page.

These all show the same error when i try to do them. It sais the error is in the below line of code.

`"delete": function (e, t) {
                var n = this;
                this.loading = !0, this.$http["delete"](e, {body: t}).then(function (e) {
                    window.eventHub.$emit("media-manager-reload-folder"), n.mediaManagerNotify(e.data.success), n.close()
                }, function (e) {
                    var t = e.data.error ? e.data.error : e.statusText;
                    n.mediaManagerNotify(t, "danger"), n.close()
                })
            }`

Im using the most recent version of media manager along with laravel 5.5

I can upload files and create new folders (when not using the modal) even rename them but not delete them and i cannot use the media modal.

**Comment by talvbansal** [comment]
Hi @mckenzieflavius,

Please see this repo for an example of how to integrate the media manager: 
https://github.com/talvbansal/media-manager-laravel-example

without seeing your code theres not a lot more that i can do so hopefully the above link helps you.

Thanks

**Comment by mckenzieflavius** [comment]
I've used the link youve given me and the same error persists, i cannot delete a picture after uploading, when i go to do it i get this error

`Failed to load resource: the server responded with a status of 404 (Not Found)
app.js:44661 Uncaught (in promise) TypeError: Cannot read property 'error' of undefined
    at app.js:44661
    at <anonymous>`

**Comment by talvbansal** [comment]
Looks like in the last lot of refactoring i made a couple if mistakes on the delete component that should be fixed now - i really need to start testing the Vue components
