### ISSUE TITLE
laravel-media-manager-example issue

### ISSUE THREAD

**Issue by mckenzieflavius** [talvbansal/media-manager#77]
I've used the link youve given me and the same error persists, i cannot delete a picture after uploading, when i go to do it i get this error

Failed to load resource: the server responded with a status of 404 (Not Found) app.js:44661 Uncaught (in promise) TypeError: Cannot read property 'error' of undefined at app.js:44661 at <anonymous>

I've cloned and followed the instructions on the example page but i get the same error using the current version of https://github.com/talvbansal/media-manager-laravel-example

**Comment by talvbansal** [comment]
I've updated the repo with the latest version of the media-manager that fixes this issue, please can you confirm its working as expected and close this :)

**Comment by mckenzieflavius** [comment]
@talvbansal I will test it tomorrow if thats alright and let you know

**Comment by mckenzieflavius** [comment]
Working fine now, can delete items.
