### ISSUE TITLE
webPath stripping out custom server port

### ISSUE THREAD

**Issue by kmare** [talvbansal/media-manager#78]
The file returned by the server to the vue component has the wrong webPath url if the server listens to a custom port. Eg the url
`http://localhost:8000/storage/kitten.jpg` 
will become 
`http://localhost/storage/kitten.jpg`

Thank you for such a nice package!

**Comment by talvbansal** [comment]
Hi @kmare!

Thanks for your kind words about the package!

Have you updated the `APP_URL` value in your .env file to include the port number?

Thanks

**Comment by kmare** [comment]
I'm sorry, I was certain I changed it so I thought it was some url parsing issue on the laravel side! 

Thank you for the quick response!
