### ISSUE TITLE
files with extension in uppercase aren't recognized (.JPG, etc.)

### ISSUE THREAD

**Issue by partikule** [talvbansal/media-manager#82]
Some camera output files with extension in uppercase.
It is common to have one picture called "IMG_3063.JPG" for example.
In that case, the picture isn't displayed by the media-manager.

To correct it, edit the file : **vendor/talvbansal/media-manager/src/Services/MediaManager.php**, method **fileMimeType()** : 

Replace : 

`$type = $this->mimeDetect->findType(pathinfo($path, PATHINFO_EXTENSION));
`
by : 

`$type = $this->mimeDetect->findType(strtolower(pathinfo($path, PATHINFO_EXTENSION)));
`

**Comment by talvbansal** [comment]
Amazing work :+1:
