### ISSUE TITLE
Implementing this as a vue component

### ISSUE THREAD

**Issue by NeoMarine** [talvbansal/media-manager#97]
Hello,

I currently use vue in my laravel project, and want to include <media-manager> within a vue component of my own that gets displayed.

Because media manager works by creating it's own vue, it doesn't seem to be able to co-exist within another vue component.

For example, if I do this in my .js file included on a page, it won't work:
`//Include the media manager
require('./../assets/talvbansal/media-manager/js/media-manager');

//Create a new vue
var editor = new Vue({
	el: '#app',
	provide () {
		return {
			doSomething: true
		}
	},`

Is there any work-around other than me dissecting your project to attempt to use it?

Note that I am using laravel 5.7, so the resources folder has been restructured since then, but that doesn't seem to be an issue - I just adjust the require path for media manager.

**Comment by talvbansal** [comment]
Hi @NeoMarine,

Sorry for the late reply im out travelling untill the EOY and my data access has been somewhat limited.

Thanks for checking out the project, if im understanding you correctly what you're trying to do is totally achiveable please see the example repo to see how its implemented within another project:

https://github.com/talvbansal/media-manager-laravel-example

Hopefully that'll help you, if not let me know and we can dig into this some more.

Thanks

Talv

**Comment by talvbansal** [comment]
Hi @NeoMarine,

I've just pushed an update to the example project so that its now running laravel 5.7 hopefully that will help you get started :).

I am in the process of re-writing a lot of the code so its much easier to scaffold and can be installed as a vue plugin. Whilst im travelling i don't have access to my main development machine but once I am back I intend to continue work on the project.

thanks

Talv

**Comment by NeoMarine** [comment]
Hi @talvbansal,

I haven't had time to fully test just yet, but I've managed to have it displaying now at least. I had to include the line **"//Include the media manager
require('./../assets/talvbansal/media-manager/js/media-manager');"** directly after **"window.Vue = require('vue');"** , otherwise vue wouldn't load on screen (without errors). Strange!

I'm going to continue working with your example and update if any issues :)
